springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

spring:
  datasource:
    username: root
    url: jdbc:h2:mem:tags_ms
    driverClassName: org.h2.Driver
    password: root
  h2:
    console:
      enabled: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: 'true'

server:
  port: 8080
  shutdown: graceful
  error:
    include-binding-errors: always
    include-message: always
